### ISSUE TITLE
load balancing HttpSolrServer 

### ISSUE THREAD

**Issue by edsanz** [enigmo/rsolr-cloud#2]
I see that your application keeps track of all the solr URLs sent by zookeeper.  How are you deciding which solr servers to query and it what order? Is it sending requests on a round robin load balancing mode?  Perhaps rsolr is the one doing it but I can't find a method in rsolr-cloud doing load balancing.

This is similar to this.
https://lucene.apache.org/solr/4_5_0/solr-solrj/org/apache/solr/client/solrj/impl/LBHttpSolrServer.html

Which is called from here:
https://lucene.apache.org/solr/4_5_0/solr-solrj/org/apache/solr/client/solrj/impl/CloudSolrServer.html

**Comment by kmrshntr** [comment]
I made this gem referring the implementation of those java classes.

CloudSolrServer passes [randomly shuffled](https://github.com/apache/lucene-solr/blob/46f0546c3c0747508dc48d98e481a561feb0b66f/solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudSolrClient.java#L1087) solr url list to LBHttpSolrServer.
LBHttpSolrServer sends request to first url in the url list. And if the request fails, it send another request to next url in the list until success. This implementation is [here](https://github.com/apache/lucene-solr/blob/6fe1d09c91d2d8c239268554126e29f4b3dbaf9a/solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttpSolrClient.java#L298).

This rsolr-cloud just sends request randomly selected url from alive solr url list in zookeeper.
The decision logic is [here](https://github.com/enigmo/rsolr-cloud/blob/4dece74492206795f935655b7f0947fe750c5f4d/lib/rsolr/cloud/connection.rb#L36).  Just calling Array#sample.

I think this is too primitive implementation so we should implement retrying logic like LBHttpSolrServer for higher fault tolerance someday.

But I couldn't find any load balancing logic in rsolr. That's why I made this gem.

**Comment by edsanz** [comment]
Thank you for answering my question and for sending me the links to the implementations.  I will be using your gem and I might send you some updates in the future.  With so many people using the SolrCloud with multiple servers I expect your gem to be used by a lot of projects.

**Comment by kmrshntr** [comment]
Then, I'll be looking forward your feedback. Thank you. :smile:
